### ISSUE TITLE
setup for haskell language server

### ISSUE THREAD

**Issue by hududed** [jecaro/dotfiles#2]
Hi Jean

wondering if your config repo here needs to be adjusted to the blog post you wrote https://jeancharles.quillet.org/posts/2021-05-14-Viming-Haskell-in-2021.html to get the HLS up and running?

**Comment by jecaro** [comment]
Hi @hududed That blog post has been written last year and explains the configuration I had at this time. My configuration has greatly evolved since then mostly to be able to handle different neovim & LSP configurations depending on the project I'm working on. I still heavily rely on haskell-language-server for my day to day work.

If you're interested in the configuration I had at the time of writing this blog post, feel free to dive into the git history of this repo. I'm not sure it would still work as some of the plugins I'm using has been updated since.

If you only want to have haskell-language-server up and running in neovim, you need:
* a recent version of neovim (at least 0.6)
* haskell-language-server in your path
* and the plugin [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig). The README of this plugin should be enough to get you started.
